obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.09, -0.06], [-0.09, 0.06], [0.025, 0.08], [0.025, -0.08]]
#robot_radius: 0.105

inflation_radius: 0.1
cost_scaling_factor: 90.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}


